name: Daily Monitoring

on:
  schedule:
    - cron: '0 8 * * *'  # Thực hiện vào lúc 8 giờ sáng mỗi ngày

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run the monitor script
        run: python monitor.py
